language: php
php:
    - 5.5
    - 5.6
    - 7

before_script:
    - git clone https://github.com/widuu/php_nanomsg.git
    - cd php_nanomsg
    - ./configure --prefix="${HOME}/php_nanomsg-master"
    - make CFLAGS="`pkg-config libnanomsg --cflags`" LDFLAGS="`pkg-config libnanomsg --libs`"
    - make install
    - cd ..


script:
    - phpize
    - ./configure --with-nanomsg="${HOME}/nanomsg-master"
    - make CFLAGS="`pkg-config libnanomsg --cflags`" LDFLAGS="`pkg-config libnanomsg --libs`"
    - export NO_INTERACTION=1
    - export REPORT_EXIT_STATUS=1
    - export TEST_PHP_EXECUTABLE=`which php`
    - php run-tests.php -d extension=nanomsg.so -d extension_dir=modules -n ./tests/*.phpt
    - for i in `ls tests/*.out 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done